version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: tunfin-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tunfin_ledger
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tunfin-net

  redis:
    image: redis:7-alpine
    container_name: tunfin-redis
    ports:
      - "6379:6379"
    networks:
      - tunfin-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    container_name: tunfin-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - tunfin-net

  kafka:
    image: confluentinc/cp-kafka:7.3.0
    container_name: tunfin-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - tunfin-net

networks:
  tunfin-net:
    driver: bridge

volumes:
  postgres_data:
